### ISSUE TITLE
arquillian remote container 

### ISSUE THREAD

**Issue by jwatts21** [arquillian/arquillian-extension-byteman#1]
The profile for the remote container is not working, receiving NoClassDefFoundError on org.jboss.byteman.agent.submit.Submit at org.jboss.arquillian.extension.byteman.impl.common.SubmitUtil.install

Some things I noticed, the managed-container(which does work) writes out a byteman.jar that's been created in DeploymentAppender.createAuxiliaryArchive to c:/tmp. 

The Submit.class, ScriptText.class and others have been added to this jar via DeploymentAppender.createAuxiliaryArchive; then the classloader in SubmitUtil.intall loads the org.jboss.byteman.agent.submit.Submit from c:\tmp

The remote-container is not writng this jar to c:\tmp, therefore I'm guessing that's cause of the NoClassDefFoundError; same classloader is being used and throwing NoClassDefFoundError.

Also I'm set the following in the standalone.bat:
JAVA_OPTS= %JAVA_OPTS% -Djboss.modules.system.pkgs=com.sun.tools.attach,org.jboss.byteman -Dorg.jboss.byteman.transform.all -javaagent:G:\lib\byteMan\byteman.jar=boot:G:\lib\byteMan\byteman.jar,listener:true

Thanks

**Comment by bartoszmajsak** [comment]
Hi there,

better late than never - just wanted to inform you that we have tested and documented required steps in [README.md](https://github.com/arquillian/arquillian-extension-byteman#how-to-run-the-tests). If you are still using this extension please let us know that helps.
