### ISSUE TITLE
Problem running on JDK9 and above

### ISSUE THREAD

**Issue by rachmatowicz** [arquillian/arquillian-extension-byteman#25]
The project's pom has the following dependency:
    \<dependency\>
    \<groupId>com.sun\</groupId>
    \<artifactId>tools\</artifactId>
    \<version>1.6.0\</version>
    \<scope>system\</scope>
    \<systemPath>${path.tools_jar}\</systemPath>
    \</dependency>
This dependency can only be satisfied for JDK 8 and below, as tools.jar has been removed from the JDK with the introduction of jigsaw. 

When I include the arquillian-byteman-extension in my ARQ-based testsuite, which I want to run on JDK 9, this dependency can't be satisfied and my testsuite will not execute. JDK 9 was released in September 2017.

I'll probably be submitting a fix for this shortly as I can't work around it.

**Comment by rachmatowicz** [comment]
I managed to fix the setup for JDK 9 so that tools.jar is no longer added to the bootclasspath via -Xbootclasspath:/a<path> and also added -Djdk.attach.allowAttachSelf=true to get around a VM attach error (VMs can't attach to themselves in JDK 9). 

However, I now find that there is another JDK 9 issue with the arquillian-chameleon, an extension used to start the containers in the tests:  https://github.com/arquillian/arquillian-container-chameleon/issues/90
This issue was opened about a year ago, but the original issue was opened 4 years ago.

**Comment by bartoszmajsak** [comment]
> This issue was opened about a year ago, but the original issue was opened 4 years ago.

Original issue, if I'm not mistaken, was "opened" on wildfly dev mailing list, which is not closely monitored by us, so that's not a surprise that it went unnoticed.

Fix for Chameleon is landing soon https://github.com/arquillian/arquillian-container-chameleon/tree/jdk9_fix

**Comment by rachmatowicz** [comment]
This issue is a bit of a puzzle. 

When the test uses the annotation @RunAsClient, when run on JDK 9, the patch in https://github.com/arquillian/arquillian-extension-byteman/pull/26 works. The class com.sun.tools.attach.VirtualMachine is found, and is successfully used to attach to itself.
 
When the test is run in the container, the test fails with the exception:
` java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine`

indicating that the code in the deployment cannot load the class. However, the JDK 9 module "jdk.attach" is visible in the list of modules available to the deployment, and the class can be loaded using 
`ClassLoader.getSystemClassLoader().loadClass("com.sun.tools.attach.VirtualMachine");
`
but not using: 
`Thread.currentThread().getContextClassLoader().loadClass("com.sun.tools.attach.VirtualMachine");`

**Comment by bartoszmajsak** [comment]
Can you point me to the test suite you are referring to in the issue description? That would help to investigate it further.

Is the `jdk.attach` available in the container you are trying to run your test in?

**Comment by fl4via** [comment]
@rachmatowicz FYI ^ see question above

**Comment by rachmatowicz** [comment]
@bartoszmajsak 

1. The testsuite i'm referring to is the testsuite for the project arquillian-extension-byteman, which makes use of chameleon. There are two types of tests in the testsuite: tests which run in-container and tests which run as standalone clients. The in-container tests (e.g. org.jboss.arquillian.extension.byteman.test.container.BindingFollowUpTestCase.java) are the ones that are failing.
The container i'm using is wildfly:11.0.0.Final:managed running under JDK 9. As I mentioned in the comment above, the jdk.attack is visible in some classloaders accessible from the container, but not the one used by the deployment.

**Comment by bartoszmajsak** [comment]
Thanks for the details @rachmatowicz. I was under the impression that you are referring to some more other, project-specific test suite which I don't have a knowledge of. I will investigate this problem in the coming week and come back to you in this issue.

**Comment by bartoszmajsak** [comment]
@rachmatowicz seems to be working with a small fix, please have a look on your original PR comment https://github.com/arquillian/arquillian-extension-byteman/pull/26#issuecomment-508169235

**Comment by bartoszmajsak** [comment]
Fixed by 32c361d
